developers = [
	"ALEXANDER DOMINIC CHAVEZ SALAS",
	"BRAYAN EMILIO GARCIA RENGIFO",
	"MICHAEL SECARLOS APAZA CALSIN",
]

ui_designers = [
	"MARIANA GRETHEL YUCRA MACHACCA",
	"VALERY BYRNE MACIAS"
]

sound_effects = [
	"DENILSON EDGARDO FLORES VALDIVIA",
]
